version: '3'

services:
  selenium-hub:
    image: selenium/hub:4.40.0
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid

  node-chrome:
    image: selenium/node-chrome:4.40.0
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - grid
    depends_on:
      - selenium-hub

  node-firefox:
    image: selenium/node-firefox:4.40.0
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid
    depends_on:
      - selenium-hub

networks:
  grid:
    driver: bridge
